name: 脚本名称
# 触发脚本的条件，deploy分支push代码的时候
on:
  push:
    branches:
      - deploy
# 要执行的任务
jobs:
  # 任务名称
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境（必填）
    runs-on: ubuntu-latest
    # 任务步骤
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master

      # 安装node
      - name: 安装node.js
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.1
      # - name: 进入server服务
      #   run: cd server
      # 安装依赖
      - name: 安装依赖
        run: cd server && npm install

      # 打包
      - name: 打包
        run: cd server && npm run webpack:build

      # - name: pkg
      #   run: cd server && npm run pkg
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: '124.222.140.199'
          username: 'root'
          key: ${{secrets.xiongxiao}}
          source: './server/dist/*'
          target: '/root/apps/short-link-server'
          strip_components: 2
      - name: executing remote ssh commands
        # 使用appleboy/ssh-action@master来执行命令
        uses: appleboy/ssh-action@master
        with:
          username: 'root'
          host: '124.222.140.199'
          key: ${{secrets.xiongxiao}}
          # linux需要安装apt install nodejs
          script: |
            echo "Hello Deploy "
            whereis node
            whereis npm
            whoami
            sh /root/apps/short-link-server/reload.sh
            exit
